name: release

on:
  push:
    branches:
      - main

jobs:
  generate-go-client:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install openapi generator
      run: npm install @openapitools/openapi-generator-cli -g
    - name: Generate Go client
      run: make
    - name: Push to client repo
      uses: actions/upload-artifact@v2
      with:
        name: client-code
        path: ./build/output/ProxmoxGo
    - name: Checkout client repo
      uses: actions/checkout@v2
      with:
        repository: awlsring/proxmox-go
        token: ${{ secrets.GO_GITHUB_TOKEN }}
    - name: ls
      run: ls -la
    - name: Download client code
      uses: actions/download-artifact@v2
      with:
        name: client-code
        path: /tmp/package
    - name: ls
      run: ls -la
    - name: Remove junk and move client code
      run: |
        rm -rf proxmox/*
        rm -rf api/*
        rm -rf docs/*
        mv /tmp/package/*.go proxmox/
        mv /tmp/package/api/* api/
        mv /tmp/package/docs/* docs/
        go mod tidy
    - name: ls
      run: ls -la
    - name: Commit and push changes
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add .
        git commit -m "automated client code update"
        git push